
import { Match, Matchday } from './listoneService';

// Calendario completo Serie A 2026/27 - Aggiornato al 7 settembre 2026
export const SERIE_A_CALENDAR: Matchday[] = [
  {
    giornata: 1,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Sassuolo' },
      { homeTeam: 'Bologna', awayTeam: 'Lazio' },
      { homeTeam: 'Frosinone', awayTeam: 'Juventus' },
      { homeTeam: 'Genoa', awayTeam: 'Napoli' },
      { homeTeam: 'Inter', awayTeam: 'Monza' },
      { homeTeam: 'Parma', awayTeam: 'Cagliari' },
      { homeTeam: 'Roma', awayTeam: 'Fiorentina' },
      { homeTeam: 'Torino', awayTeam: 'Milan' },
      { homeTeam: 'Udinese', awayTeam: 'Como' },
      { homeTeam: 'Venezia', awayTeam: 'Lecce' },
    ],
  },
  {
    giornata: 2,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Bologna' },
      { homeTeam: 'Cagliari', awayTeam: 'Inter' },
      { homeTeam: 'Fiorentina', awayTeam: 'Frosinone' },
      { homeTeam: 'Juventus', awayTeam: 'Parma' },
      { homeTeam: 'Lazio', awayTeam: 'Genoa' },
      { homeTeam: 'Lecce', awayTeam: 'Roma' },
      { homeTeam: 'Milan', awayTeam: 'Venezia' },
      { homeTeam: 'Monza', awayTeam: 'Udinese' },
      { homeTeam: 'Napoli', awayTeam: 'Como' },
      { homeTeam: 'Sassuolo', awayTeam: 'Torino' },
    ],
  },
  {
    giornata: 3,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Sassuolo' },
      { homeTeam: 'Cagliari', awayTeam: 'Lecce' },
      { homeTeam: 'Fiorentina', awayTeam: 'Torino' },
      { homeTeam: 'Frosinone', awayTeam: 'Venezia' },
      { homeTeam: 'Genoa', awayTeam: 'Como' },
      { homeTeam: 'Inter', awayTeam: 'Napoli' },
      { homeTeam: 'Juventus', awayTeam: 'Milan' },
      { homeTeam: 'Parma', awayTeam: 'Monza' },
      { homeTeam: 'Roma', awayTeam: 'Atalanta' },
      { homeTeam: 'Udinese', awayTeam: 'Lazio' },
    ],
  },
  {
    giornata: 4,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Cagliari' },
      { homeTeam: 'Como', awayTeam: 'Parma' },
      { homeTeam: 'Genoa', awayTeam: 'Frosinone' },
      { homeTeam: 'Inter', awayTeam: 'Udinese' },
      { homeTeam: 'Lazio', awayTeam: 'Milan' },
      { homeTeam: 'Lecce', awayTeam: 'Monza' },
      { homeTeam: 'Napoli', awayTeam: 'Bologna' },
      { homeTeam: 'Sassuolo', awayTeam: 'Juventus' },
      { homeTeam: 'Torino', awayTeam: 'Roma' },
      { homeTeam: 'Venezia', awayTeam: 'Fiorentina' },
    ],
  },
  {
    giornata: 5,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Torino' },
      { homeTeam: 'Fiorentina', awayTeam: 'Napoli' },
      { homeTeam: 'Frosinone', awayTeam: 'Como' },
      { homeTeam: 'Juventus', awayTeam: 'Atalanta' },
      { homeTeam: 'Milan', awayTeam: 'Lecce' },
      { homeTeam: 'Monza', awayTeam: 'Sassuolo' },
      { homeTeam: 'Parma', awayTeam: 'Genoa' },
      { homeTeam: 'Roma', awayTeam: 'Inter' },
      { homeTeam: 'Udinese', awayTeam: 'Cagliari' },
      { homeTeam: 'Venezia', awayTeam: 'Lazio' },
    ],
  },
  {
    giornata: 6,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Venezia' },
      { homeTeam: 'Cagliari', awayTeam: 'Juventus' },
      { homeTeam: 'Como', awayTeam: 'Roma' },
      { homeTeam: 'Genoa', awayTeam: 'Fiorentina' },
      { homeTeam: 'Inter', awayTeam: 'Parma' },
      { homeTeam: 'Lazio', awayTeam: 'Monza' },
      { homeTeam: 'Lecce', awayTeam: 'Bologna' },
      { homeTeam: 'Napoli', awayTeam: 'Frosinone' },
      { homeTeam: 'Sassuolo', awayTeam: 'Milan' },
      { homeTeam: 'Torino', awayTeam: 'Udinese' },
    ],
  },
  {
    giornata: 7,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Inter' },
      { homeTeam: 'Fiorentina', awayTeam: 'Como' },
      { homeTeam: 'Frosinone', awayTeam: 'Sassuolo' },
      { homeTeam: 'Juventus', awayTeam: 'Lazio' },
      { homeTeam: 'Milan', awayTeam: 'Atalanta' },
      { homeTeam: 'Monza', awayTeam: 'Cagliari' },
      { homeTeam: 'Parma', awayTeam: 'Torino' },
      { homeTeam: 'Roma', awayTeam: 'Genoa' },
      { homeTeam: 'Udinese', awayTeam: 'Lecce' },
      { homeTeam: 'Venezia', awayTeam: 'Napoli' },
    ],
  },
  {
    giornata: 8,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Frosinone' },
      { homeTeam: 'Cagliari', awayTeam: 'Bologna' },
      { homeTeam: 'Como', awayTeam: 'Sassuolo' },
      { homeTeam: 'Genoa', awayTeam: 'Venezia' },
      { homeTeam: 'Inter', awayTeam: 'Fiorentina' },
      { homeTeam: 'Lazio', awayTeam: 'Parma' },
      { homeTeam: 'Lecce', awayTeam: 'Juventus' },
      { homeTeam: 'Napoli', awayTeam: 'Roma' },
      { homeTeam: 'Torino', awayTeam: 'Monza' },
      { homeTeam: 'Udinese', awayTeam: 'Milan' },
    ],
  },
  {
    giornata: 9,
    matches: [
      { homeTeam: 'Fiorentina', awayTeam: 'Atalanta' },
      { homeTeam: 'Frosinone', awayTeam: 'Lecce' },
      { homeTeam: 'Genoa', awayTeam: 'Juventus' },
      { homeTeam: 'Milan', awayTeam: 'Bologna' },
      { homeTeam: 'Monza', awayTeam: 'Napoli' },
      { homeTeam: 'Parma', awayTeam: 'Udinese' },
      { homeTeam: 'Roma', awayTeam: 'Cagliari' },
      { homeTeam: 'Sassuolo', awayTeam: 'Lazio' },
      { homeTeam: 'Torino', awayTeam: 'Como' },
      { homeTeam: 'Venezia', awayTeam: 'Inter' },
    ],
  },
  {
    giornata: 10,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Parma' },
      { homeTeam: 'Bologna', awayTeam: 'Monza' },
      { homeTeam: 'Como', awayTeam: 'Venezia' },
      { homeTeam: 'Frosinone', awayTeam: 'Torino' },
      { homeTeam: 'Juventus', awayTeam: 'Napoli' },
      { homeTeam: 'Lazio', awayTeam: 'Cagliari' },
      { homeTeam: 'Lecce', awayTeam: 'Genoa' },
      { homeTeam: 'Milan', awayTeam: 'Inter' },
      { homeTeam: 'Sassuolo', awayTeam: 'Fiorentina' },
      { homeTeam: 'Udinese', awayTeam: 'Roma' },
    ],
  },
  {
    giornata: 11,
    matches: [
      { homeTeam: 'Cagliari', awayTeam: 'Frosinone' },
      { homeTeam: 'Fiorentina', awayTeam: 'Juventus' },
      { homeTeam: 'Genoa', awayTeam: 'Milan' },
      { homeTeam: 'Inter', awayTeam: 'Como' },
      { homeTeam: 'Monza', awayTeam: 'Atalanta' },
      { homeTeam: 'Napoli', awayTeam: 'Lazio' },
      { homeTeam: 'Parma', awayTeam: 'Bologna' },
      { homeTeam: 'Roma', awayTeam: 'Sassuolo' },
      { homeTeam: 'Torino', awayTeam: 'Lecce' },
      { homeTeam: 'Venezia', awayTeam: 'Udinese' },
    ],
  },
  {
    giornata: 12,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Inter' },
      { homeTeam: 'Bologna', awayTeam: 'Udinese' },
      { homeTeam: 'Como', awayTeam: 'Cagliari' },
      { homeTeam: 'Juventus', awayTeam: 'Venezia' },
      { homeTeam: 'Lazio', awayTeam: 'Lecce' },
      { homeTeam: 'Milan', awayTeam: 'Frosinone' },
      { homeTeam: 'Monza', awayTeam: 'Fiorentina' },
      { homeTeam: 'Napoli', awayTeam: 'Torino' },
      { homeTeam: 'Parma', awayTeam: 'Roma' },
      { homeTeam: 'Sassuolo', awayTeam: 'Genoa' },
    ],
  },
  {
    giornata: 13,
    matches: [
      { homeTeam: 'Cagliari', awayTeam: 'Milan' },
      { homeTeam: 'Como', awayTeam: 'Juventus' },
      { homeTeam: 'Frosinone', awayTeam: 'Parma' },
      { homeTeam: 'Inter', awayTeam: 'Genoa' },
      { homeTeam: 'Lecce', awayTeam: 'Atalanta' },
      { homeTeam: 'Roma', awayTeam: 'Monza' },
      { homeTeam: 'Sassuolo', awayTeam: 'Napoli' },
      { homeTeam: 'Torino', awayTeam: 'Lazio' },
      { homeTeam: 'Udinese', awayTeam: 'Fiorentina' },
      { homeTeam: 'Venezia', awayTeam: 'Bologna' },
    ],
  },
  {
    giornata: 14,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Roma' },
      { homeTeam: 'Fiorentina', awayTeam: 'Cagliari' },
      { homeTeam: 'Frosinone', awayTeam: 'Inter' },
      { homeTeam: 'Genoa', awayTeam: 'Torino' },
      { homeTeam: 'Juventus', awayTeam: 'Udinese' },
      { homeTeam: 'Lazio', awayTeam: 'Atalanta' },
      { homeTeam: 'Milan', awayTeam: 'Parma' },
      { homeTeam: 'Monza', awayTeam: 'Como' },
      { homeTeam: 'Napoli', awayTeam: 'Lecce' },
      { homeTeam: 'Venezia', awayTeam: 'Sassuolo' },
    ],
  },
  {
    giornata: 15,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Genoa' },
      { homeTeam: 'Cagliari', awayTeam: 'Venezia' },
      { homeTeam: 'Como', awayTeam: 'Bologna' },
      { homeTeam: 'Inter', awayTeam: 'Torino' },
      { homeTeam: 'Juventus', awayTeam: 'Monza' },
      { homeTeam: 'Lazio', awayTeam: 'Roma' },
      { homeTeam: 'Lecce', awayTeam: 'Sassuolo' },
      { homeTeam: 'Napoli', awayTeam: 'Milan' },
      { homeTeam: 'Parma', awayTeam: 'Fiorentina' },
      { homeTeam: 'Udinese', awayTeam: 'Frosinone' },
    ],
  },
  {
    giornata: 16,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Napoli' },
      { homeTeam: 'Fiorentina', awayTeam: 'Bologna' },
      { homeTeam: 'Frosinone', awayTeam: 'Lazio' },
      { homeTeam: 'Genoa', awayTeam: 'Udinese' },
      { homeTeam: 'Lecce', awayTeam: 'Inter' },
      { homeTeam: 'Milan', awayTeam: 'Como' },
      { homeTeam: 'Roma', awayTeam: 'Juventus' },
      { homeTeam: 'Sassuolo', awayTeam: 'Parma' },
      { homeTeam: 'Torino', awayTeam: 'Cagliari' },
      { homeTeam: 'Venezia', awayTeam: 'Monza' },
    ],
  },
  {
    giornata: 17,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Juventus' },
      { homeTeam: 'Cagliari', awayTeam: 'Genoa' },
      { homeTeam: 'Como', awayTeam: 'Lecce' },
      { homeTeam: 'Fiorentina', awayTeam: 'Lazio' },
      { homeTeam: 'Inter', awayTeam: 'Sassuolo' },
      { homeTeam: 'Monza', awayTeam: 'Milan' },
      { homeTeam: 'Parma', awayTeam: 'Napoli' },
      { homeTeam: 'Roma', awayTeam: 'Frosinone' },
      { homeTeam: 'Torino', awayTeam: 'Venezia' },
      { homeTeam: 'Udinese', awayTeam: 'Atalanta' },
    ],
  },
  {
    giornata: 18,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Como' },
      { homeTeam: 'Frosinone', awayTeam: 'Bologna' },
      { homeTeam: 'Genoa', awayTeam: 'Monza' },
      { homeTeam: 'Juventus', awayTeam: 'Torino' },
      { homeTeam: 'Lazio', awayTeam: 'Inter' },
      { homeTeam: 'Lecce', awayTeam: 'Parma' },
      { homeTeam: 'Milan', awayTeam: 'Fiorentina' },
      { homeTeam: 'Napoli', awayTeam: 'Cagliari' },
      { homeTeam: 'Sassuolo', awayTeam: 'Udinese' },
      { homeTeam: 'Venezia', awayTeam: 'Roma' },
    ],
  },
  {
    giornata: 19,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Genoa' },
      { homeTeam: 'Cagliari', awayTeam: 'Sassuolo' },
      { homeTeam: 'Como', awayTeam: 'Lazio' },
      { homeTeam: 'Fiorentina', awayTeam: 'Lecce' },
      { homeTeam: 'Inter', awayTeam: 'Juventus' },
      { homeTeam: 'Monza', awayTeam: 'Frosinone' },
      { homeTeam: 'Parma', awayTeam: 'Venezia' },
      { homeTeam: 'Roma', awayTeam: 'Milan' },
      { homeTeam: 'Torino', awayTeam: 'Atalanta' },
      { homeTeam: 'Udinese', awayTeam: 'Napoli' },
    ],
  },
  {
    giornata: 20,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Roma' },
      { homeTeam: 'Cagliari', awayTeam: 'Como' },
      { homeTeam: 'Juventus', awayTeam: 'Genoa' },
      { homeTeam: 'Lazio', awayTeam: 'Bologna' },
      { homeTeam: 'Lecce', awayTeam: 'Udinese' },
      { homeTeam: 'Milan', awayTeam: 'Torino' },
      { homeTeam: 'Napoli', awayTeam: 'Fiorentina' },
      { homeTeam: 'Parma', awayTeam: 'Inter' },
      { homeTeam: 'Sassuolo', awayTeam: 'Monza' },
      { homeTeam: 'Venezia', awayTeam: 'Frosinone' },
    ],
  },
  {
    giornata: 21,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Atalanta' },
      { homeTeam: 'Como', awayTeam: 'Napoli' },
      { homeTeam: 'Fiorentina', awayTeam: 'Sassuolo' },
      { homeTeam: 'Frosinone', awayTeam: 'Milan' },
      { homeTeam: 'Genoa', awayTeam: 'Parma' },
      { homeTeam: 'Inter', awayTeam: 'Venezia' },
      { homeTeam: 'Juventus', awayTeam: 'Cagliari' },
      { homeTeam: 'Lecce', awayTeam: 'Torino' },
      { homeTeam: 'Monza', awayTeam: 'Lazio' },
      { homeTeam: 'Roma', awayTeam: 'Udinese' },
    ],
  },
  {
    giornata: 22,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Fiorentina' },
      { homeTeam: 'Cagliari', awayTeam: 'Parma' },
      { homeTeam: 'Genoa', awayTeam: 'Lecce' },
      { homeTeam: 'Lazio', awayTeam: 'Venezia' },
      { homeTeam: 'Milan', awayTeam: 'Juventus' },
      { homeTeam: 'Monza', awayTeam: 'Roma' },
      { homeTeam: 'Napoli', awayTeam: 'Inter' },
      { homeTeam: 'Sassuolo', awayTeam: 'Como' },
      { homeTeam: 'Torino', awayTeam: 'Frosinone' },
      { homeTeam: 'Udinese', awayTeam: 'Bologna' },
    ],
  },
  {
    giornata: 23,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Lazio' },
      { homeTeam: 'Bologna', awayTeam: 'Milan' },
      { homeTeam: 'Como', awayTeam: 'Monza' },
      { homeTeam: 'Fiorentina', awayTeam: 'Udinese' },
      { homeTeam: 'Inter', awayTeam: 'Cagliari' },
      { homeTeam: 'Juventus', awayTeam: 'Sassuolo' },
      { homeTeam: 'Lecce', awayTeam: 'Napoli' },
      { homeTeam: 'Parma', awayTeam: 'Frosinone' },
      { homeTeam: 'Roma', awayTeam: 'Torino' },
      { homeTeam: 'Venezia', awayTeam: 'Genoa' },
    ],
  },
  {
    giornata: 24,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Como' },
      { homeTeam: 'Cagliari', awayTeam: 'Lazio' },
      { homeTeam: 'Frosinone', awayTeam: 'Fiorentina' },
      { homeTeam: 'Genoa', awayTeam: 'Atalanta' },
      { homeTeam: 'Inter', awayTeam: 'Milan' },
      { homeTeam: 'Monza', awayTeam: 'Lecce' },
      { homeTeam: 'Napoli', awayTeam: 'Juventus' },
      { homeTeam: 'Roma', awayTeam: 'Parma' },
      { homeTeam: 'Torino', awayTeam: 'Sassuolo' },
      { homeTeam: 'Udinese', awayTeam: 'Venezia' },
    ],
  },
  {
    giornata: 25,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Monza' },
      { homeTeam: 'Como', awayTeam: 'Torino' },
      { homeTeam: 'Fiorentina', awayTeam: 'Inter' },
      { homeTeam: 'Juventus', awayTeam: 'Bologna' },
      { homeTeam: 'Lazio', awayTeam: 'Napoli' },
      { homeTeam: 'Lecce', awayTeam: 'Frosinone' },
      { homeTeam: 'Milan', awayTeam: 'Genoa' },
      { homeTeam: 'Sassuolo', awayTeam: 'Roma' },
      { homeTeam: 'Udinese', awayTeam: 'Parma' },
      { homeTeam: 'Venezia', awayTeam: 'Cagliari' },
    ],
  },
  {
    giornata: 26,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Lecce' },
      { homeTeam: 'Cagliari', awayTeam: 'Udinese' },
      { homeTeam: 'Como', awayTeam: 'Milan' },
      { homeTeam: 'Frosinone', awayTeam: 'Napoli' },
      { homeTeam: 'Genoa', awayTeam: 'Lazio' },
      { homeTeam: 'Inter', awayTeam: 'Atalanta' },
      { homeTeam: 'Monza', awayTeam: 'Juventus' },
      { homeTeam: 'Parma', awayTeam: 'Sassuolo' },
      { homeTeam: 'Roma', awayTeam: 'Venezia' },
      { homeTeam: 'Torino', awayTeam: 'Fiorentina' },
    ],
  },
  {
    giornata: 27,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Torino' },
      { homeTeam: 'Fiorentina', awayTeam: 'Venezia' },
      { homeTeam: 'Juventus', awayTeam: 'Roma' },
      { homeTeam: 'Lazio', awayTeam: 'Frosinone' },
      { homeTeam: 'Lecce', awayTeam: 'Como' },
      { homeTeam: 'Milan', awayTeam: 'Cagliari' },
      { homeTeam: 'Monza', awayTeam: 'Genoa' },
      { homeTeam: 'Napoli', awayTeam: 'Parma' },
      { homeTeam: 'Sassuolo', awayTeam: 'Bologna' },
      { homeTeam: 'Udinese', awayTeam: 'Inter' },
    ],
  },
  {
    giornata: 28,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Napoli' },
      { homeTeam: 'Cagliari', awayTeam: 'Fiorentina' },
      { homeTeam: 'Como', awayTeam: 'Udinese' },
      { homeTeam: 'Frosinone', awayTeam: 'Monza' },
      { homeTeam: 'Genoa', awayTeam: 'Roma' },
      { homeTeam: 'Lazio', awayTeam: 'Juventus' },
      { homeTeam: 'Milan', awayTeam: 'Sassuolo' },
      { homeTeam: 'Parma', awayTeam: 'Lecce' },
      { homeTeam: 'Torino', awayTeam: 'Inter' },
      { homeTeam: 'Venezia', awayTeam: 'Atalanta' },
    ],
  },
  {
    giornata: 29,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Milan' },
      { homeTeam: 'Fiorentina', awayTeam: 'Genoa' },
      { homeTeam: 'Inter', awayTeam: 'Frosinone' },
      { homeTeam: 'Juventus', awayTeam: 'Como' },
      { homeTeam: 'Monza', awayTeam: 'Bologna' },
      { homeTeam: 'Napoli', awayTeam: 'Venezia' },
      { homeTeam: 'Parma', awayTeam: 'Lazio' },
      { homeTeam: 'Roma', awayTeam: 'Lecce' },
      { homeTeam: 'Sassuolo', awayTeam: 'Cagliari' },
      { homeTeam: 'Udinese', awayTeam: 'Torino' },
    ],
  },
  {
    giornata: 30,
    matches: [
      { homeTeam: 'Cagliari', awayTeam: 'Napoli' },
      { homeTeam: 'Como', awayTeam: 'Fiorentina' },
      { homeTeam: 'Frosinone', awayTeam: 'Udinese' },
      { homeTeam: 'Genoa', awayTeam: 'Inter' },
      { homeTeam: 'Lecce', awayTeam: 'Lazio' },
      { homeTeam: 'Milan', awayTeam: 'Monza' },
      { homeTeam: 'Roma', awayTeam: 'Bologna' },
      { homeTeam: 'Sassuolo', awayTeam: 'Atalanta' },
      { homeTeam: 'Torino', awayTeam: 'Juventus' },
      { homeTeam: 'Venezia', awayTeam: 'Parma' },
    ],
  },
  {
    giornata: 31,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Venezia' },
      { homeTeam: 'Cagliari', awayTeam: 'Atalanta' },
      { homeTeam: 'Fiorentina', awayTeam: 'Milan' },
      { homeTeam: 'Frosinone', awayTeam: 'Genoa' },
      { homeTeam: 'Inter', awayTeam: 'Roma' },
      { homeTeam: 'Juventus', awayTeam: 'Lecce' },
      { homeTeam: 'Lazio', awayTeam: 'Torino' },
      { homeTeam: 'Napoli', awayTeam: 'Sassuolo' },
      { homeTeam: 'Parma', awayTeam: 'Como' },
      { homeTeam: 'Udinese', awayTeam: 'Monza' },
    ],
  },
  {
    giornata: 32,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Udinese' },
      { homeTeam: 'Bologna', awayTeam: 'Cagliari' },
      { homeTeam: 'Como', awayTeam: 'Frosinone' },
      { homeTeam: 'Fiorentina', awayTeam: 'Parma' },
      { homeTeam: 'Milan', awayTeam: 'Napoli' },
      { homeTeam: 'Monza', awayTeam: 'Inter' },
      { homeTeam: 'Roma', awayTeam: 'Lazio' },
      { homeTeam: 'Sassuolo', awayTeam: 'Lecce' },
      { homeTeam: 'Torino', awayTeam: 'Genoa' },
      { homeTeam: 'Venezia', awayTeam: 'Juventus' },
    ],
  },
  {
    giornata: 33,
    matches: [
      { homeTeam: 'Cagliari', awayTeam: 'Monza' },
      { homeTeam: 'Frosinone', awayTeam: 'Roma' },
      { homeTeam: 'Genoa', awayTeam: 'Sassuolo' },
      { homeTeam: 'Inter', awayTeam: 'Bologna' },
      { homeTeam: 'Juventus', awayTeam: 'Fiorentina' },
      { homeTeam: 'Lazio', awayTeam: 'Como' },
      { homeTeam: 'Lecce', awayTeam: 'Milan' },
      { homeTeam: 'Napoli', awayTeam: 'Udinese' },
      { homeTeam: 'Parma', awayTeam: 'Atalanta' },
      { homeTeam: 'Venezia', awayTeam: 'Torino' },
    ],
  },
  {
    giornata: 34,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Juventus' },
      { homeTeam: 'Bologna', awayTeam: 'Fiorentina' },
      { homeTeam: 'Como', awayTeam: 'Inter' },
      { homeTeam: 'Lecce', awayTeam: 'Cagliari' },
      { homeTeam: 'Milan', awayTeam: 'Lazio' },
      { homeTeam: 'Monza', awayTeam: 'Venezia' },
      { homeTeam: 'Roma', awayTeam: 'Napoli' },
      { homeTeam: 'Sassuolo', awayTeam: 'Frosinone' },
      { homeTeam: 'Torino', awayTeam: 'Parma' },
      { homeTeam: 'Udinese', awayTeam: 'Genoa' },
    ],
  },
  {
    giornata: 35,
    matches: [
      { homeTeam: 'Fiorentina', awayTeam: 'Roma' },
      { homeTeam: 'Frosinone', awayTeam: 'Atalanta' },
      { homeTeam: 'Genoa', awayTeam: 'Cagliari' },
      { homeTeam: 'Inter', awayTeam: 'Lecce' },
      { homeTeam: 'Lazio', awayTeam: 'Sassuolo' },
      { homeTeam: 'Napoli', awayTeam: 'Monza' },
      { homeTeam: 'Parma', awayTeam: 'Milan' },
      { homeTeam: 'Torino', awayTeam: 'Bologna' },
      { homeTeam: 'Udinese', awayTeam: 'Juventus' },
      { homeTeam: 'Venezia', awayTeam: 'Como' },
    ],
  },
  {
    giornata: 36,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Frosinone' },
      { homeTeam: 'Cagliari', awayTeam: 'Torino' },
      { homeTeam: 'Como', awayTeam: 'Atalanta' },
      { homeTeam: 'Juventus', awayTeam: 'Inter' },
      { homeTeam: 'Lazio', awayTeam: 'Udinese' },
      { homeTeam: 'Lecce', awayTeam: 'Fiorentina' },
      { homeTeam: 'Milan', awayTeam: 'Roma' },
      { homeTeam: 'Monza', awayTeam: 'Parma' },
      { homeTeam: 'Napoli', awayTeam: 'Genoa' },
      { homeTeam: 'Sassuolo', awayTeam: 'Venezia' },
    ],
  },
  {
    giornata: 37,
    matches: [
      { homeTeam: 'Atalanta', awayTeam: 'Lecce' },
      { homeTeam: 'Fiorentina', awayTeam: 'Monza' },
      { homeTeam: 'Frosinone', awayTeam: 'Cagliari' },
      { homeTeam: 'Genoa', awayTeam: 'Bologna' },
      { homeTeam: 'Inter', awayTeam: 'Lazio' },
      { homeTeam: 'Parma', awayTeam: 'Juventus' },
      { homeTeam: 'Roma', awayTeam: 'Como' },
      { homeTeam: 'Torino', awayTeam: 'Napoli' },
      { homeTeam: 'Udinese', awayTeam: 'Sassuolo' },
      { homeTeam: 'Venezia', awayTeam: 'Milan' },
    ],
  },
  {
    giornata: 38,
    matches: [
      { homeTeam: 'Bologna', awayTeam: 'Parma' },
      { homeTeam: 'Cagliari', awayTeam: 'Roma' },
      { homeTeam: 'Como', awayTeam: 'Genoa' },
      { homeTeam: 'Juventus', awayTeam: 'Frosinone' },
      { homeTeam: 'Lazio', awayTeam: 'Fiorentina' },
      { homeTeam: 'Lecce', awayTeam: 'Venezia' },
      { homeTeam: 'Milan', awayTeam: 'Udinese' },
      { homeTeam: 'Monza', awayTeam: 'Torino' },
      { homeTeam: 'Napoli', awayTeam: 'Atalanta' },
      { homeTeam: 'Sassuolo', awayTeam: 'Inter' },
    ],
  },
];

// Funzione per ottenere le partite di una giornata specifica
export function getMatchesForGiornata(giornata: number): Match[] {
  const matchday = SERIE_A_CALENDAR.find(m => m.giornata === giornata);
  return matchday ? matchday.matches : [];
}

// Funzione per ottenere l'avversaria di una squadra in una giornata
export function getAvversariaForTeam(team: string, giornata: number): { avversario: string; inCasa: boolean } {
  const matches = getMatchesForGiornata(giornata);

  for (const match of matches) {
    if (match.homeTeam === team) {
      return { avversario: match.awayTeam, inCasa: true };
    }
    if (match.awayTeam === team) {
      return { avversario: match.homeTeam, inCasa: false };
    }
  }

  // Se non trova la partita, ritorna valori di default
  return { avversario: 'ND', inCasa: true };
}

// Funzione per applicare il calendario ai giocatori
export function applyCalendarToPlayers(players: any[], giornata: number): any[] {
  return players.map(player => {
    const matchInfo = getAvversariaForTeam(player.team, giornata);
    return {
      ...player,
      avversario: matchInfo.avversario,
      inCasa: matchInfo.inCasa,
    };
  });
}
